UBO.projectid.default                                 = eahjena
MCR.OAIDataProvider.OAI.RepositoryName                = Bibliographie, Ernst-Abbe-Hochschule Jena


# Enrichment Resolver
MCR.MODS.EnrichmentResolver.DataSources.import        = %MCR.MODS.EnrichmentResolver.DataSources.withScopus%
MCR.Cronjob.Jobs.DBT-Import.Command.Institution       = 7

######################################################################
#                                                                    #
#                                  LDAP                              #
#                                                                    #
######################################################################

MCR.user2.IdentityManagement.UserCreation.Affiliation = Ernst-Abbe-Hochschule Jena
MCR.user2.IdentityManagement.UserCreation.LDAP.Realm  = eah-jena.de
MCR.user2.LDAP.searchFilter.base                      = (&(objectClass=eduPerson)(eduPersonUniqueId=*)(|%s))
